Added WaterCommandFactory and ViewWaterCommand classes
AY2425S1-CS2113-W10-3/tp pull request #151
Opened 2024-10-24 16:01 UTC by Atulteja

Close #127
Close #122 
Close #121 
Close #115

2024-10-24 17:42 UTC, Bev-low requested changes
Overall is okay but some changes are needed

2024-10-24 17:42 UTC, Bev-low commented on src/main/java/command/water/ViewWaterCommand.java
> +        Water waterList = getWaterList(history);
actually, for this, can do this way
DailyRecord dailyRecord = history.getRecordByDate(date);
        MealList meals = dailyRecord.getMealList();
        return new CommandResult(meals.toString());
        
The way we access water and mealList is through DailyRecord

2024-10-24 17:42 UTC, Bev-low commented on src/main/java/parser/command/WaterCommandFactory.java
> +        flagParser.validateRequiredFlags("/d");
these validateRequiredFlags should not be /d as /d stands for days

2024-10-24 17:42 UTC, Bev-low commented on src/main/java/parser/command/WaterCommandFactory.java
> +        flagParser.validateRequiredFlags("/d");
same for here

2024-10-24 17:42 UTC, Bev-low commented on src/main/java/parser/command/WaterCommandFactory.java
> +        flagParser.validateRequiredFlags("/d");
and here should not have a validate

2024-10-24 23:20 UTC, Atulteja commented on src/main/java/command/water/ViewWaterCommand.java
> +        Water waterList = getWaterList(history);
it already does that in the getWaterList fucntion, same thing for meal as well, the naming is different though

2024-10-25 02:26 UTC, Bev-low approved these changes

2024-10-25 07:42 UTC, nirala-ts approved these changes

2024-10-25 07:42 UTC, nirala-ts commented on src/main/java/parser/ParserUtils.java
> +        String trimmedFloatString = floatString.trim();
LGTM

2024-10-25 13:46 UTC, merged