Update Storage and tojson and fromJson
AY2425S1-CS2113-W10-3/tp pull request #23
Opened 2024-10-07 08:03 UTC by Bev-low

Added the storage and toJson and fromJson methods. 

needed to import soemthing for the Json and there is an error for the importing.

2024-10-10 14:02 UTC, Atulteja approved these changes

2024-10-10 14:02 UTC, Atulteja commented on src/main/java/programme/ProgrammeList.java
> +    }
Everything looks good to me!

2024-10-14 02:43 UTC, TVageesan requested changes

2024-10-14 03:04 UTC, Bev-low commented on src/main/java/core/Storage.java
> +            Path filePath = directoryPath.resolve("data.json");
okay

2024-10-14 04:06 UTC, TVageesan approved these changes
LGTM

2024-10-14 04:06 UTC, merged