Add delete & create day functionality to edit command
AY2425S1-CS2113-W10-3/tp pull request #45
Opened 2024-10-10 17:03 UTC by TVageesan

2024-10-14 04:25 UTC, Bev-low requested changes
Just wanna clarify what EditSubCommand and EditExerciseCommand diff is

2024-10-14 04:25 UTC, Bev-low commented on src/main/java/command/programme/edit/CreateDayCommand.java
> +    }
yup looks good

2024-10-14 04:25 UTC, Bev-low commented on src/main/java/command/programme/edit/EditSubCommand.java
> +    public EditSubCommand(int progId, int dayId){
Can i clarify what is this for. what is this differnet from EditExercises

2024-10-14 04:25 UTC, Bev-low commented on src/main/java/parser/ProgammeParser.java
> +        };
looks good

2024-10-14 04:28 UTC, TVageesan commented on src/main/java/command/programme/edit/EditSubCommand.java
> +    public EditSubCommand(int progId, int dayId){
EditSubCommand is an abstract class for all the programme edit commands (create/remove day, create/remove/update exercise). Changed it from ExerciseCommand -> EditSubCommand because now it also edits the days in the programme, not just the exercise.

2024-10-14 11:23 UTC, andreusxcarvalho approved these changes

2024-10-15 05:46 UTC, Bev-low approved these changes

2024-10-15 05:51 UTC, merged